### ISSUE TITLE
Error estilo consola - lstlisting

### ISSUE THREAD

**Issue by davidcawork** [jmrplens/TFG-TFM_EPS#6]
Buenas,

Antes que nada me gustaría agradecer el trabajo realizado con la plantilla, es increíble. No soy estudiante de la Universidad de Alicante, actualmente estoy estudiando en la Universidad de Alcalá pero he terminado haciendo uso de esta plantilla, ya que  me parecía muy bonita y trabajada. Tuve que hacer uso de otra plantilla que ofrecía un profesor de mi universidad para sustituir las portadas de esta, por las oficiales que imponen en la normativa de mi uni.  Pero de verdad, mil gracias 😄. Dejo aquí la descripción de un error que me he encontrado al trabajar con la plantilla, y como lo he resuelto, por si fuera de utilidad.

El error se encontró a la hora de insertar código de un script en bash, con el estilo consolas:

```bash
\begin{lstlisting}[language= bash, style=Consola, caption={ejemplo bash 2},label=bash2]
   sudo apt install -y bison flex libmnl-dev libdb5.3-dev
\end{lstlisting}
```

Comentar que estoy trabajando en Overleaf, por si tuviera alguna implicación en el origen del error.  El error que me daba al compilar la memoria era el siguiente:

```bash
Class srcbook Error: undefined old font command '\bf'.
```

Comprobando la definición del estilo ```Consolas``` vi que hacia uso de ese comando, entiendo que la motivación era que se viera en negrita. Por lo visto parecía que ese comando era antiguo, y ya no estaba definido. Su equivalente según este [post](https://tex.stackexchange.com/questions/346870/bf-is-an-undefined-command) es el siguiente:

```bash
\DeclareOldFontCommand{\bf}{\normalfont\bfseries}{\mathbf}
```

Haciendo uso de esta declaración, el comando ya se encontraba definido y el error dejo de persistir.

Muchas gracias de nuevo por su trabajo,

**Comment by jmrplens** [comment]
Hola, perdona, no había visto las issues de este repositorio (y no había recibido notificación señores de GitHub...).

Muchas gracias por valorar el trabajo. Hay tantas cosas que al final siempre salen detalles que corregir. He reproducido lo que me indicabas y es cierto que estaba mal pero si no vas a hacer uso de `\bf` en ninguna otra parte del documento es mejor cambiar solo en la definición del formato del código (el archivo `estiloscodigosprogramacion.tex`):
Antes:
```latex
\lstdefinestyle{Consola}
	{
	basicstyle=\scriptsize\bf\ttfamily,
	}
```
Después:
```latex
\lstdefinestyle{Consola}
	{
	basicstyle=\scriptsize\bfseries\ttfamily,
	}
```

Yo voy a actualizar el archivo del repositorio para que no vuelva a ocurrir. Muchas gracias por el aviso!
