### ISSUE TITLE
Lista de acrónimos 

### ISSUE THREAD

**Issue by Hassio108** [jmrplens/TFG-TFM_EPS#7]
He compilado la plantilla tal cual (sin hacer ninguna modificación) y no aparece la lista de acrónimos y abreviaturas. He empleado XeLatex y las aplicaciones de Texpad (Mac) y TeXstudio (Windows) y ocurre lo mismo siempre.
¿Alguna idea de cómo puede solucionarse?

Un saludo.

**Comment by jmrplens** [comment]
Hola, perdona, no había visto este issue.

He intentado reproducir el error en Texpad pero siguen apareciéndome la lista de acrónimos.
En Texpad asegurate de que en el 'Typesetter', en el apartado de 'Indices' esté marcada la opción de 'Acronyms.

En Texstudio si que me ha ocurrido y lo he solucionado creando una orden nueva en 'Preferencias->Compilar->Ordenes de Usuario', la orden es: `xelatex -synctex=1 -interaction=nonstopmode %.tex|makeglossaries %|xelatex -synctex=1
-interaction=nonstopmode %.tex|xelatex -synctex=1 -interaction=nonstopmode %.tex`, al crearla aparecera en el menú 'Herramientas->Usuario->TuOrden', al ejecutarla compilará creando la lista.
Es posible que haya soluciones más optimas pero ahora mismo no recuerdo otro modo de hacerlo.

Un saludo

**Comment by ijm11** [comment]
Hay que tener en cuenta de que debe estar instalado 'perl'. En mi caso, no lo tenía instalado previamente en mi equipo y tuve que instalarlo, reiniciar el editor TexStudio y ya funcionaba.
